# Generated by Django 5.1.7 on 2026-02-11 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd pul'), ('click', 'Click orqali'), ('payme', 'Payme orqali'), ('cart', 'Plastik orqali'), ('other', 'boshqa tolov turi orqali')], max_length=50)),
                ('status', models.CharField(choices=[('new', 'Yangi buyurtma'), ('waiting', 'Kutulmoqda...'), ('in_progress', 'Jarayonda...'), ('waiting_pay', 'Tolov qilish Kutilmoqda...'), ('delivering', 'Yetkazib berilmoqda...'), ('deliveried', 'Yetkazib berilgan.'), ('complated', 'Tugallangan.'), ('cancalled_by_customer', 'Mijoz tomondan bekor qilingan'), ('cancalled_by_seller', 'Sotuvchi tomonidan bekor qilingan')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('total_price', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
